__stryx__:
  schema: __main__:Config
  created_at: '2025-12-15T10:54:42.482449+00:00'
  overrides:
  - optimizer.lr=5e-5
  - train.epochs=50
exp_name: dataclass_demo
model: bert-base
train:
  epochs: 50
  batch_size: 32
  seed: 42
optimizer:
  lr: 5.0e-05
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.999
eval_config: null
